apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
       - name: MONGODB_URI
          value: "mongodb://mongodb:27017/myDatabase"  # Match this to your MongoDB deployment
        - name: SESSION_SECRET
          value: "1234"
        - name: EMAIL_USER
          value: "chagantyteja2502@gmail.com"
        - name: EMAIL_PASS
          value: "yxoq bjuk rdnt alzp"
        - name: PORT
          value: "3130"    
