apiVersion: v1 
kind: Pod 
metadata: 
  name: empty-dir-pod 
spec:
  restartPolicy: Never
  containers:
    - image: busybox
      name: busybox1 
      command: ['sh','-c','while true;do echo Sucess!! > /output/output.txt;sleep 5;done']
      volumeMounts:
        - name: my-volume
          mountPath: /output        
  volumes:
    - name: my-volume
      emptyDir: {}    