apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: organic-app-rs 
spec:
  replicas: 3
  selector:
    matchLabels:
      web: app
  template: # Define the Pod Defination 
    metadata:
      labels:
        web: app 
    spec:
      containers:
        - name: sample-cont 
          image: muralisocial123/organic-app-web:latest
          ports:
            - containerPort: 5656