apiVersion: v1 
kind: Pod 
metadata:
  name: env-pod 
spec:
  containers:
    - image: busybox 
      name: busybox 
      command: ['sh', '-c', 'while true; do echo configmap is : $CONFIGMAPVAR and secret is $SECRETVAR; sleep 10; done ']
      env:
        - name: CONFIGMAPVAR 
          valueFrom:
            configMapKeyRef:
              name: my-config 
              key: name 
        - name: SECRETVAR 
          valueFrom:
            secretKeyRef:
              name:  my-secret-example
              key:  secret1  
