apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cart-application-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: test-cont
        image: muralisocial123/cart-page-test:1.0
        ports:
        - containerPort: 3000
