apiVersion: v1 
kind: Pod 
metadata:
  name: test-pod 
  namespace: test-ns
spec: 
  containers:
    - image: muralisocial123/cart-page-test:1.0
      name: test-cont 
      ports:
        - containerPort: 3000
